/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "background":                "#f7f9fb",
        "surface":                   "#f7f9fb",
        "surface-bright":            "#f7f9fb",
        "surface-dim":               "#d8dadc",
        "surface-container-lowest":  "#ffffff",
        "surface-container-low":     "#f2f4f6",
        "surface-container":         "#eceef0",
        "surface-container-high":    "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "surface-variant":           "#e0e3e5",
        "on-surface":                "#191c1e",
        "on-surface-variant":        "#41484d",
        "outline":                   "#71787e",
        "outline-variant":           "#c1c7ce",
        "inverse-surface":           "#2d3133",
        "inverse-on-surface":        "#eff1f3",

        "primary":                   "#2e6385",
        "on-primary":                "#ffffff",
        "primary-container":         "#a5d8ff",
        "on-primary-container":      "#285f80",
        "primary-fixed":             "#c9e6ff",
        "primary-fixed-dim":         "#9accf3",
        "on-primary-fixed":          "#001e2f",
        "on-primary-fixed-variant":  "#0c4b6c",
        "inverse-primary":           "#9accf3",
        "surface-tint":              "#2e6385",

        "secondary":                 "#4d6073",
        "on-secondary":              "#ffffff",
        "secondary-container":       "#cde2f9",
        "on-secondary-container":    "#516578",
        "secondary-fixed":           "#d0e5fb",
        "secondary-fixed-dim":       "#b4c9df",
        "on-secondary-fixed":        "#071d2e",
        "on-secondary-fixed-variant":"#35495b",

        "tertiary":                  "#7d5718",
        "on-tertiary":               "#ffffff",
        "tertiary-container":        "#fdc97f",
        "on-tertiary-container":     "#785313",
        "tertiary-fixed":            "#ffddb2",
        "tertiary-fixed-dim":        "#f1be75",
        "on-tertiary-fixed":         "#291800",
        "on-tertiary-fixed-variant": "#624000",

        "error":                     "#ba1a1a",
        "on-error":                  "#ffffff",
        "error-container":           "#ffdad6",
        "on-error-container":        "#93000a",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body:     ["Inter", "sans-serif"],
        label:    ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        "2xl":   "0.75rem",
        full:    "0.75rem",
      },
      boxShadow: {
        arctic: "0px 20px 40px rgba(24, 44, 61, 0.06)",
      },
    },
  },
  plugins: [],
};
