"""
Site scraper: extracts competitor metadata from competition result website HTML pages.

PDFs contain scores (technical, components, elements) but often lack metadata
that is only present on the website: club, birth year, starting number, category, etc.

This module scrapes the HTML site and returns structured competitor info
that can be merged with PDF-parsed scores during import.

The scraper is extensible: register site-specific scrapers via `register_scraper`.

## Supported site formats

- **FrenchIJSScraper**: handles French figure skating competition result sites
  generated by the IJS-compatible software widely used by the FFSG and regional
  leagues (e.g. ligue-occitanie-sg.com, ffsg.org, …).  The expected layout is:
    - An ``index.htm`` page with a table listing events and links to sub-pages.
    - Per-event ``.htm`` pages with a results table (rank, bib, name, club, score).
  Names are typically ALL-CAPS; the scraper title-cases them automatically.
- **GenericTableScraper**: heuristic fallback for any statically generated site
  that exposes results in HTML tables.
"""

from __future__ import annotations

import logging
import re
import unicodedata
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from urllib.parse import urljoin, urlparse

import httpx
from bs4 import BeautifulSoup, Tag

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class ScrapedCompetitor:
    """Competitor metadata extracted from the competition website."""
    name: str
    nationality: str | None = None
    club: str | None = None
    birth_year: int | None = None
    category: str | None = None
    segment: str | None = None
    starting_number: int | None = None
    rank: int | None = None
    total_score: float | None = None
    # Extra fields that don't fit elsewhere
    extra: dict = field(default_factory=dict)


@dataclass
class ScrapedEvent:
    """An event (category + segment) found on the competition index page."""
    name: str                        # e.g. "Espoirs Dames 1"
    results_url: str | None = None   # link to HTML results page
    pdf_urls: list[str] = field(default_factory=list)  # links to PDF protocols


# ---------------------------------------------------------------------------
# Abstract base
# ---------------------------------------------------------------------------

class BaseSiteScraper(ABC):
    @abstractmethod
    def can_handle(self, url: str) -> bool:
        """Return True if this scraper knows how to handle the given site."""

    @abstractmethod
    async def scrape(self, url: str, client: httpx.AsyncClient) -> list[ScrapedCompetitor]:
        """Scrape the competition site and return competitor metadata."""

    async def discover_events(
        self, url: str, client: httpx.AsyncClient
    ) -> list[ScrapedEvent]:
        """
        Return high-level event list from the competition index page.
        Default implementation returns an empty list; override if meaningful.
        """
        return []


# ---------------------------------------------------------------------------
# French IJS competition scraper
# ---------------------------------------------------------------------------

class FrenchIJSScraper(BaseSiteScraper):
    """
    Scraper for French figure skating competition result sites.

    These sites are generated by the IJS-compatible software used by the FFSG
    and its regional leagues.  The typical layout is:

    index.htm
    ├── Table of events, one row per category/segment
    │   ├── Column 0: event name (e.g. "Espoirs Dames 1")
    │   ├── Column N: link to result page (.htm)
    │   └── Column M: link(s) to PDF protocols
    └── Per-event HTML pages
        └── Table with columns: Rang, N°, Patineur, Club, [Nation,] Points

    Names appear in ALL CAPS on the result pages; this scraper title-cases them.
    """

    # Columns we look for in event result tables
    _HEADER_MAP = {
        # rank
        "rang": "rank", "rank": "rank", "pl": "rank", "place": "rank",
        "clt": "rank",
        # bib / starting number
        "num": "starting_number", "n°": "starting_number", "no": "starting_number",
        "bib": "starting_number", "départ": "starting_number", "depart": "starting_number",
        # name
        "nom": "name", "name": "name", "athlete": "name", "patineur": "name",
        "patineurs": "name", "concurrent": "name",
        # club
        "club": "club", "société": "club", "societe": "club", "association": "club",
        # nationality
        "nation": "nationality", "nat": "nationality", "pays": "nationality",
        # birth year
        "né": "birth_year", "naissance": "birth_year", "born": "birth_year",
        "an.": "birth_year", "année": "birth_year",
        # score / points
        "points": "total_score", "score": "total_score", "total": "total_score",
        "pts": "total_score",
        # segment (sometimes encoded)
        "segment": "segment",
    }

    _NAT_RE = re.compile(r"^[A-Z]{2,3}$")
    _YEAR_RE = re.compile(r"\b(19[5-9]\d|20[0-2]\d)\b")
    _RANK_RE = re.compile(r"^\d{1,3}\.?$")
    _NUM_RE = re.compile(r"^\d{1,3}$")
    _SCORE_RE = re.compile(r"^\d+(?:[.,]\d+)?$")

    # Patterns that identify this scraper's domain
    _DOMAIN_HINTS = re.compile(
        r"ligue-occitanie-sg\.com|ffsg\.org|ffpatinage\.fr|patinage\.fr",
        re.IGNORECASE,
    )

    def can_handle(self, url: str) -> bool:
        return bool(self._DOMAIN_HINTS.search(url))

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    async def discover_events(
        self, url: str, client: httpx.AsyncClient
    ) -> list[ScrapedEvent]:
        html = await self._fetch(url, client)
        if html is None:
            return []
        soup = BeautifulSoup(html, "html.parser")
        return self._parse_index(soup, url)

    async def scrape(
        self, url: str, client: httpx.AsyncClient
    ) -> list[ScrapedCompetitor]:
        html = await self._fetch(url, client)
        if html is None:
            return []

        soup = BeautifulSoup(html, "html.parser")
        events = self._parse_index(soup, url)

        if not events:
            # The URL itself may be a result page (not an index)
            return self._extract_competitors(soup, category=None)

        competitors: list[ScrapedCompetitor] = []
        seen: dict[str, ScrapedCompetitor] = {}

        for event in events:
            if not event.results_url:
                continue
            event_html = await self._fetch(event.results_url, client)
            if event_html is None:
                continue
            event_soup = BeautifulSoup(event_html, "html.parser")
            for c in self._extract_competitors(event_soup, category=event.name):
                key = normalize_name(c.name)
                if key not in seen:
                    seen[key] = c
                    competitors.append(c)
                else:
                    _merge_competitor(seen[key], c)

        return competitors

    # ------------------------------------------------------------------
    # Index parsing
    # ------------------------------------------------------------------

    def _parse_index(self, soup: BeautifulSoup, base_url: str) -> list[ScrapedEvent]:
        """
        Parse the competition index page and return a list of events.

        The index table typically looks like:

            | Catégorie       | Résultats | Protocoles (PDF) |
            |-----------------|-----------|-----------------|
            | Espoirs Dames 1 | [link]    | [link]          |
        """
        events: list[ScrapedEvent] = []
        base_dir = base_url.rsplit("/", 1)[0] + "/"

        for table in soup.find_all("table"):
            rows = table.find_all("tr")
            if len(rows) < 2:
                continue

            # Detect if this looks like an event index table:
            # first row is a header; we need at least one link in subsequent rows.
            has_htm_links = any(
                re.search(r"\.htm", a.get("href", ""), re.IGNORECASE)
                for row in rows[1:]
                for a in row.find_all("a", href=True)
            )
            if not has_htm_links:
                continue

            for row in rows[1:]:
                cells = row.find_all(["td", "th"])
                if not cells:
                    continue

                # First cell = event name
                event_name = _clean_text(cells[0].get_text())
                if not event_name:
                    continue

                results_url: str | None = None
                pdf_urls: list[str] = []

                for cell in cells[1:]:
                    for a in cell.find_all("a", href=True):
                        href = a["href"]
                        abs_href = urljoin(base_dir, href)
                        if re.search(r"\.pdf$", href, re.IGNORECASE):
                            pdf_urls.append(abs_href)
                        elif re.search(r"\.html?$", href, re.IGNORECASE):
                            if results_url is None:
                                results_url = abs_href

                if event_name and (results_url or pdf_urls):
                    events.append(ScrapedEvent(
                        name=event_name,
                        results_url=results_url,
                        pdf_urls=pdf_urls,
                    ))

        return events

    # ------------------------------------------------------------------
    # Per-event result page parsing
    # ------------------------------------------------------------------

    def _extract_competitors(
        self, soup: BeautifulSoup, category: str | None
    ) -> list[ScrapedCompetitor]:
        """Extract competitors from an event result page."""
        competitors: list[ScrapedCompetitor] = []

        # Try to infer category from headings if not provided
        if not category:
            category = self._heading_category(soup)

        for table in soup.find_all("table"):
            rows = table.find_all("tr")
            if len(rows) < 2:
                continue

            col_map = self._map_columns(rows[0])
            if "name" not in col_map:
                # Try second row as header (some pages have a merged title row)
                if len(rows) >= 3:
                    col_map = self._map_columns(rows[1])
                    data_rows = rows[2:]
                else:
                    continue
            else:
                data_rows = rows[1:]

            if "name" not in col_map:
                continue

            for row in data_rows:
                cells = row.find_all(["td", "th"])
                if not cells:
                    continue
                c = self._parse_result_row(cells, col_map, category)
                if c:
                    competitors.append(c)

        return competitors

    def _map_columns(self, header_row: Tag) -> dict[str, int]:
        col_map: dict[str, int] = {}
        cells = header_row.find_all(["th", "td"])
        for i, cell in enumerate(cells):
            raw = cell.get_text(strip=True).lower()
            normalized = _strip_accents(raw).strip(" .:*/")
            for keyword, field_name in self._HEADER_MAP.items():
                if keyword in normalized and field_name not in col_map:
                    col_map[field_name] = i
                    break
        return col_map

    def _parse_result_row(
        self,
        cells: list[Tag],
        col_map: dict[str, int],
        category: str | None,
    ) -> ScrapedCompetitor | None:
        def cell_text(field: str) -> str | None:
            idx = col_map.get(field)
            if idx is None or idx >= len(cells):
                return None
            return cells[idx].get_text(strip=True) or None

        raw_name = cell_text("name")
        if not raw_name or len(raw_name) < 2:
            return None
        name = _title_case_name(raw_name)

        rank: int | None = None
        rank_raw = cell_text("rank")
        if rank_raw:
            m = re.match(r"^(\d{1,3})\.?$", rank_raw.strip())
            if m:
                rank = int(m.group(1))

        starting_number: int | None = None
        sn_raw = cell_text("starting_number")
        if sn_raw and self._NUM_RE.match(sn_raw):
            starting_number = int(sn_raw)

        club = cell_text("club")
        if club:
            club = _clean_text(club)

        nationality = cell_text("nationality")
        if nationality and not self._NAT_RE.match(nationality):
            nationality = None

        birth_year: int | None = None
        by_raw = cell_text("birth_year")
        if by_raw:
            m = self._YEAR_RE.search(by_raw)
            if m:
                birth_year = int(m.group(1))

        total_score: float | None = None
        score_raw = cell_text("total_score")
        if score_raw:
            # Accept both "." and "," as decimal separator
            score_raw = score_raw.replace(",", ".")
            if self._SCORE_RE.match(score_raw):
                try:
                    total_score = float(score_raw)
                except ValueError:
                    pass

        segment = cell_text("segment")

        return ScrapedCompetitor(
            name=name,
            nationality=nationality,
            club=club,
            birth_year=birth_year,
            category=category,
            segment=segment,
            starting_number=starting_number,
            rank=rank,
            total_score=total_score,
        )

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _heading_category(soup: BeautifulSoup) -> str | None:
        for tag in soup.find_all(["h1", "h2", "h3", "h4", "caption"]):
            text = _clean_text(tag.get_text())
            if text and len(text) > 3:
                return text
        return None

    @staticmethod
    async def _fetch(url: str, client: httpx.AsyncClient) -> str | None:
        try:
            resp = await client.get(url, follow_redirects=True)
            if resp.status_code != 200:
                logger.warning("HTTP %d fetching %s", resp.status_code, url)
                return None
            # Auto-detect encoding: French sites often use latin-1/windows-1252
            if resp.encoding and resp.encoding.lower() in ("utf-8", "utf8"):
                return resp.text
            # Try declared charset; fall back to windows-1252
            content_type = resp.headers.get("content-type", "")
            charset_match = re.search(r"charset=([^\s;]+)", content_type, re.IGNORECASE)
            declared = charset_match.group(1) if charset_match else None
            encoding = declared or "windows-1252"
            return resp.content.decode(encoding, errors="replace")
        except Exception as exc:
            logger.warning("Failed to fetch %s: %s", url, exc)
            return None


# ---------------------------------------------------------------------------
# Generic fallback scraper (unchanged behaviour, small improvements)
# ---------------------------------------------------------------------------

class GenericTableScraper(BaseSiteScraper):
    """
    Generic scraper that looks for HTML tables containing competitor data.

    Heuristic approach:
    - Finds tables that likely contain rankings (columns: rank/name/club/nation/score)
    - Follows links to sub-pages (categories) and scrapes those too
    - Best-effort: works reasonably well on statically generated sites
    """

    _NAT_RE = re.compile(r"^[A-Z]{2,3}$")
    _YEAR_RE = re.compile(r"\b(19[5-9]\d|20[0-2]\d)\b")
    _RANK_RE = re.compile(r"^\d{1,3}\.?$")
    _NUM_RE = re.compile(r"^\d{1,3}$")
    _SCORE_RE = re.compile(r"^\d+(?:[.,]\d+)?$")

    _HEADER_MAP = {
        "rang": "rank", "rank": "rank", "pl": "rank", "place": "rank",
        "clt": "rank",
        "num": "starting_number", "n°": "starting_number", "no": "starting_number",
        "bib": "starting_number", "départ": "starting_number",
        "nom": "name", "name": "name", "athlete": "name", "patineur": "name",
        "patineurs": "name", "concurrent": "name",
        "club": "club", "société": "club", "societe": "club",
        "nation": "nationality", "nat": "nationality", "pays": "nationality",
        "né": "birth_year", "naissance": "birth_year", "born": "birth_year",
        "an.": "birth_year",
        "catégorie": "category", "cat": "category", "category": "category",
        "segment": "segment",
        "points": "total_score", "score": "total_score", "total": "total_score",
        "pts": "total_score",
    }

    def can_handle(self, url: str) -> bool:
        return True  # fallback

    async def scrape(self, url: str, client: httpx.AsyncClient) -> list[ScrapedCompetitor]:
        pages = await self._collect_pages(url, client)
        competitors: list[ScrapedCompetitor] = []
        seen: dict[str, ScrapedCompetitor] = {}

        for _page_url, html, category_hint in pages:
            soup = BeautifulSoup(html, "html.parser")
            for c in self._extract_from_page(soup, category_hint):
                key = normalize_name(c.name)
                if key not in seen:
                    seen[key] = c
                    competitors.append(c)
                else:
                    _merge_competitor(seen[key], c)

        return competitors

    async def _collect_pages(
        self, url: str, client: httpx.AsyncClient
    ) -> list[tuple[str, str, str | None]]:
        pages: list[tuple[str, str, str | None]] = []
        visited: set[str] = set()
        base_path = url.rsplit("/", 1)[0] + "/"

        async def fetch_page(page_url: str, category: str | None) -> None:
            if page_url in visited:
                return
            visited.add(page_url)
            try:
                resp = await client.get(page_url, follow_redirects=True)
                if resp.status_code != 200:
                    return
                # Best-effort encoding
                try:
                    html = resp.content.decode(resp.encoding or "windows-1252", errors="replace")
                except Exception:
                    html = resp.text
                pages.append((page_url, html, category))

                soup = BeautifulSoup(html, "html.parser")
                for a in soup.find_all("a", href=True):
                    href = a["href"]
                    if not href or href.startswith("#") or href.startswith("mailto"):
                        continue
                    abs_href = urljoin(page_url, href)
                    if abs_href.startswith(base_path) and abs_href not in visited:
                        if re.search(r"\.(htm|html)$", abs_href, re.IGNORECASE):
                            hint = a.get_text(strip=True) or category
                            await fetch_page(abs_href, hint)
            except Exception as exc:
                logger.debug("Skipping %s: %s", page_url, exc)

        await fetch_page(url, None)
        return pages

    def _extract_from_page(
        self, soup: BeautifulSoup, category_hint: str | None
    ) -> list[ScrapedCompetitor]:
        competitors: list[ScrapedCompetitor] = []

        category = category_hint
        if not category:
            for tag in soup.find_all(["h1", "h2", "h3", "h4", "caption"]):
                text = _clean_text(tag.get_text())
                if text:
                    category = text
                    break

        for table in soup.find_all("table"):
            rows = table.find_all("tr")
            if len(rows) < 2:
                continue

            headers = [
                _strip_accents(th.get_text(strip=True)).lower().strip(" .:*/")
                for th in rows[0].find_all(["th", "td"])
            ]
            col_map = self._map_columns(headers)

            if "name" not in col_map:
                continue

            for row in rows[1:]:
                cells = row.find_all(["td", "th"])
                if not cells:
                    continue
                c = self._parse_row(cells, col_map, category)
                if c:
                    competitors.append(c)

        return competitors

    def _map_columns(self, headers: list[str]) -> dict[str, int]:
        col_map: dict[str, int] = {}
        for i, h in enumerate(headers):
            for keyword, field_name in self._HEADER_MAP.items():
                if keyword in h and field_name not in col_map:
                    col_map[field_name] = i
                    break
        return col_map

    def _parse_row(
        self, cells: list[Tag], col_map: dict[str, int], category: str | None
    ) -> ScrapedCompetitor | None:
        def cell_text(field: str) -> str | None:
            idx = col_map.get(field)
            if idx is None or idx >= len(cells):
                return None
            return cells[idx].get_text(strip=True) or None

        raw_name = cell_text("name")
        if not raw_name or len(raw_name) < 3:
            return None
        name = _title_case_name(raw_name)

        club = cell_text("club")
        nationality = cell_text("nationality")
        if nationality and not self._NAT_RE.match(nationality):
            nationality = None

        birth_year: int | None = None
        by_raw = cell_text("birth_year")
        if by_raw:
            m = self._YEAR_RE.search(by_raw)
            if m:
                birth_year = int(m.group(1))

        rank: int | None = None
        rank_raw = cell_text("rank")
        if rank_raw:
            m = re.match(r"^(\d{1,3})\.?$", rank_raw.strip())
            if m:
                rank = int(m.group(1))

        starting_number: int | None = None
        sn_raw = cell_text("starting_number")
        if sn_raw and self._NUM_RE.match(sn_raw):
            starting_number = int(sn_raw)

        total_score: float | None = None
        score_raw = cell_text("total_score")
        if score_raw:
            score_raw = score_raw.replace(",", ".")
            if self._SCORE_RE.match(score_raw):
                try:
                    total_score = float(score_raw)
                except ValueError:
                    pass

        segment = cell_text("segment")
        cat_col = cell_text("category")

        return ScrapedCompetitor(
            name=name,
            nationality=nationality,
            club=club,
            birth_year=birth_year,
            category=cat_col or category,
            segment=segment,
            starting_number=starting_number,
            rank=rank,
            total_score=total_score,
        )


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

def normalize_name(name: str) -> str:
    """Normalize a skater name for fuzzy matching between HTML and PDF sources."""
    name = _strip_accents(name).lower()
    name = re.sub(r"[^a-z\s]", "", name)
    return " ".join(name.split())


def _strip_accents(text: str) -> str:
    return "".join(
        c for c in unicodedata.normalize("NFD", text)
        if unicodedata.category(c) != "Mn"
    )


def _clean_text(text: str) -> str:
    """Collapse whitespace and strip leading/trailing spaces."""
    return " ".join(text.split())


def _title_case_name(name: str) -> str:
    """
    Convert an ALL-CAPS French name to title case.

    French names frequently appear in ALL CAPS on competition result pages.
    Examples:
        "DUPONT MARIE"     → "Dupont Marie"
        "DE LA FONTAINE"   → "de la Fontaine"   (particle lowercased)
        "Dupont Marie"     → "Dupont Marie"      (already mixed-case: untouched)

    Only converts if the name is all-uppercase; mixed-case names are left as-is
    to avoid corrupting names that were already entered correctly.
    """
    stripped = name.strip()
    # If not all-uppercase, return as-is (preserve intentional mixed case)
    alpha_chars = [c for c in stripped if c.isalpha()]
    if not alpha_chars or not all(c.isupper() for c in alpha_chars):
        return stripped

    # French lowercase particles
    _PARTICLES = {"de", "du", "des", "le", "la", "les", "d", "l", "van", "von", "da"}

    parts = stripped.split()
    result = []
    for i, part in enumerate(parts):
        lower = part.lower()
        if i > 0 and lower in _PARTICLES:
            result.append(lower)
        else:
            result.append(part.capitalize())
    return " ".join(result)


def _merge_competitor(target: ScrapedCompetitor, source: ScrapedCompetitor) -> None:
    """Fill in missing fields in target from source."""
    for f in (
        "nationality", "club", "birth_year", "category",
        "segment", "starting_number", "rank", "total_score",
    ):
        if getattr(target, f) is None and getattr(source, f) is not None:
            setattr(target, f, getattr(source, f))
    target.extra.update({k: v for k, v in source.extra.items() if k not in target.extra})


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------

_scrapers: list[BaseSiteScraper] = [
    FrenchIJSScraper(),   # checked first; falls back to generic if can_handle() is False
    GenericTableScraper(),
]


def register_scraper(scraper: BaseSiteScraper, priority: bool = True) -> None:
    """Register a new site scraper. Set priority=True to insert before existing ones."""
    if priority:
        _scrapers.insert(0, scraper)
    else:
        _scrapers.append(scraper)


def _select_scraper(url: str) -> BaseSiteScraper:
    for s in _scrapers:
        if s.can_handle(url):
            return s
    return _scrapers[-1]


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

async def scrape_competition_site(url: str) -> list[ScrapedCompetitor]:
    """
    Scrape a competition result website and return competitor metadata.
    Results can be merged with PDF-parsed scores during import.
    """
    async with httpx.AsyncClient(
        timeout=30.0,
        headers={"User-Agent": "Mozilla/5.0 (compatible; skating-analyzer/1.0)"},
    ) as client:
        scraper = _select_scraper(url)
        return await scraper.scrape(url, client)


async def discover_competition_events(url: str) -> list[ScrapedEvent]:
    """
    Return the list of events found on a competition index page.
    Useful for pre-flight checks and selective downloading.
    """
    async with httpx.AsyncClient(
        timeout=30.0,
        headers={"User-Agent": "Mozilla/5.0 (compatible; skating-analyzer/1.0)"},
    ) as client:
        scraper = _select_scraper(url)
        return await scraper.discover_events(url, client)


def build_lookup(competitors: list[ScrapedCompetitor]) -> dict[str, ScrapedCompetitor]:
    """Build a {normalized_name: ScrapedCompetitor} dict for quick lookup during import."""
    return {normalize_name(c.name): c for c in competitors}
